  json.id @transaction.id
  json.transaction_date @transaction.transaction_date
  json.name @transaction.name
  json.amount @transaction.amount
  json.pending @transaction.pending
  json.category_id @transaction.category_id
  json.category_info @transaction.category_name
  json.account_id @transaction.account_id
  json.account_name @transaction.account_name
  json.user_id @transaction.user_id